// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyldvfyylsncpqeifrpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bGR2Znl5bHNuY3BxZWlmcnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjYzMzksImV4cCI6MjA2NTcwMjMzOX0.APRCx4V9TkpvpiD20qREc-vEAx5h9XrG_1baeyDg4Gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);